### ISSUE TITLE
t/91manifest.t fails if any extra file present in workdir

### ISSUE THREAD

**Issue by AdUser** [tonycoz/imager-file-avif#1]
Please consider rewrite this test in more reliable way, if it meaning was "ensure all needed files present", maniread() and loop with "-f $file" should be more than enough.

    $ prove -l t/91manifest.t 
    t/91manifest.t .. ok                                                               
    All tests successful.
    Files=1, Tests=1,  0 wallclock secs ( 0.02 usr  0.00 sys +  0.07 cusr  0.01 csys =  0.10 CPU)
    Result: PASS    
    $
    $ mkdir -p debian/patches
    $ touch debian/patches/series
    $
    $ prove -l t/91manifest.t                                                                                                     
    t/91manifest.t .. 1/?                                                                                                                                                 
    #   Failed test 'check manifind vs MANIFEST'                                       
    #   at t/91manifest.t line 16.
    #     Structures begin differing at:
    #          $got->[7] = 'imavif.c'                                                  
    #     $expected->[7] = 'debian/patches/series'

**Comment by tonycoz** [comment]
This behaves as intended, it tests both that the files in the MANIFEST are there *and* during development that I've updated MANIFEST to include the files or MANIFEST.SKIPped them.

I'll make it require AUTOMATED_TESTING/IMAGER_AUTHOR_TESTING though.
