### ISSUE TITLE
misleading note in manpage

### ISSUE THREAD

**Issue by AdUser** [tonycoz/imager-file-avif#2]
Manpage says:

         # type won't be necessary if the extension is avif from Imager 1.008
         $img->write(file => "foo.avif", type => "avif")
           or die $img->errstr;

But in fact .avif support was added much later, [in 1.016](https://github.com/tonycoz/imager/commit/0ad6e37442e261598b31debb818eb15a43134804), you may mix it up with .webp support. At least, imager's version from debian bullseye (1.012) still not recognizes .avif files without explicit "type" passed to read()

Also, will be helpful if you mention proper way to use add_type_extensions() to achive this behaviour on older versions

**Comment by tonycoz** [comment]
Thanks.

I started the AVIF module by copying the WEBP module and forgot to update the version.  Thanks for the report, and this is fixed in 0.002.
